### ISSUE TITLE
Can it run without Kubernetes?

### ISSUE THREAD

**Issue by TerenceLiu98** [nils-braun/codehub#1]
A great integration of Kubernetes, Jupyter and vscode! I want to try it without the Kubernetes environment, could you give me some hints? :)

**Comment by nils-braun** [comment]
Hi @TerenceLiu98 !
Thanks :-)
I see two possibilities here:
* you run a small k8s setup by yourself. There are quite simple options like "kind" or "minikube" or "microk8s". Those are quite simple to install and give you a one-cluster k8s with the same options as a large one. You can fine more information [here](https://kubernetes.io/de/docs/setup/).
* In principle you can also rebuild everything in this project with just docker and a lot of boilerplate code. You would need to start building a Jupyter Hub with the settings specified in this project (in the values file). Additionally, you need the docker spawner (instead of the k8s spawner) and probably some more configs.

I am happy to walk you through one of the options in more detail. I would recommend the first option, as it is a lot less work :-)

**Comment by TerenceLiu98** [comment]
Thanks for the advice! I have tried the second option and I think it may cause a lot of time in writing the spawner, which is not I am familiar with. I will try the first option in the following days. Thanks again for the quick response!

**Comment by TerenceLiu98** [comment]
BTW, let me explain why I am trying to build this system in physical machine:

I am a cluster admin and I want to use the jupyterhub as a web portal which can let the user login and use the Code-Server as their "WebIDE".

**Comment by nils-braun** [comment]
Hi @TerenceLiu98 

that is a nice idea! Let me try to understand your use case better, maybe I can even help you writing (or even using) one of the spawners for JupyterHub.

* So you have a cluster of machines (or a single machine?) where users can log in (I guess they have some sort of home folders on a network share and you have defined the users as "normal" Linux users)
* you want the users to log in on a single URL via JupyterHub, which then gets forwarded to one of the machines in your cluster, where a VS Code instance is started, correct? 
* Do you want users to start their "own" Code instance (like: they need to install the binaries and configure the settings of VSCode by themself) or do you want to provide them with a finished setup?
* You are not running any kind of containerization (e.g. docker) or k8s

If my assumptions are correct, we might be able to "quickly" build something with the [SSH Spawner](https://github.com/NERSC/sshspawner/blob/master/jupyterhub_config.py) or anything derived from it. Just get in touch with me if you would like to work on this together with me

**Comment by TerenceLiu98** [comment]
Thanks for the replying! @nils-braun  

Yes, it is a cluster with multiple machine running a job scheduling system ([SLURM](https://slurm.schedmd.com/documentation.html)).  Each user has its own home folder in the Control Node. What I want to do is the users logging in  a single URL via JupyterHub and the run the VS Code instance start on their own home folder. 
* Here is a situation I need to tell you: I can only use some port on the server for "the security problem" (banned directly by the server room's route). 
* What I have tried is using the `[cloudflared](https://github.com/cloudflare/cloudflared)` to set up the proxy tunnel  and the user can use VS Code / Code-Server. (here is the script: [code-server proxy](https://gist.github.com/TerenceLiu98/0c7746f130666c8e5a81601bd6b26b2a#gistcomment-3815602))
* However, these script still needs user to log in to server via the SSH. (Most of our user has little experience in `terminal`, so I want to avoid it)

As far as I know, the Code-Server needs multiple ports for multiple singleusers and I am confusing in how to set up a proxy server between JupyterHub and Code-Server.

**Comment by TerenceLiu98** [comment]
@nils-braun  I think I have solved the problem via the [betatim/vscode-binder](https://github.com/betatim/vscode-binder), which provides a `jupyter-vscode-proxy`. 

1. user will log in the system via the JupyterHub (as we proposed to)
2. then, they log in to the JupyterLab and start the VS Code with single click
3. finally, they can use a functional Code-Server hosting on the Control Node

Here is the rendering:

<a href="https://sm.ms/image/1tcj4TDWqEX7aM9" target="_blank"><img src="https://i.loli.net/2021/07/18/1tcj4TDWqEX7aM9.gif" height="400" width="400" /></a>

Although it cannot directly redirect to the `/vscode/`,  I think it is a big step on my work.

Thanks again for your kindly advising!

**Comment by nils-braun** [comment]
That is really cool! I did not know about this plugin. Looks good!

If you want, you can at least build URLs in the schema "hub/user-redirect/vscode" which works for all users and is quite close to just a "/vscode" (see [here](https://jupyterhub.readthedocs.io/en/stable/reference/urls.html#user-redirect)). Maybe that works?

**Comment by TerenceLiu98** [comment]
I have removed the `@jupyterlab/notebook-extension` and set `760` permission to the system python, In this way, the user without `sudo` cannot turn on the Jupyter-Notebook or use the console. This is because I don't want them "ruin" the system python environment. However, they can still use the JupyterLab to check their file tree.  :)
